server:
  port: 9090


logging:
  level:
    org.springframework: INFO
    com.cs: DEBUG
    
 
    
app:
  pluginDir: "./plugin"
  outpath: "./data"
  persistFile: "./dl.json"
  parallel_downloads: 10
  ThreadsPerDownload: 1
  proxytype: "HTTP"
  proxyhost: "192.168.0.100"
  proxyport: 8118
   
spring:
  application:
    name: mein-projekt
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:downloaddb
    driverClassName: org.h2.Driver
    username: sa
    password:
    name: h2db
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
springdoc:
  api-docs:
    path: "/api-docs"

plugin:
  monitoringPath: "./plugin"