server:
  port: 9092

logging:
  level:
    org.springframework: INFO
    com.cs: DEBUG

download:
  outpath: "./data"
  persistfile: "./dl.json"
  paralleldownloads: 10
  downloadthreads: 1
  
dockertor:    
  path: "%userprofile%/.docker"
  registryurl: "om.local:5000"
  host: 192.168.0.100
  torpassword: "kali"
  workdir: "./config"
  file: "C:/Users/sonst00m/Documents/Privat/05-Hobby/Project/downloader/downloader/download-service-tor/config/tor/Dockerfile"
  sshport: 22
  sshuser: "kali"
  sshpassword: "kali"
  dockerport: 2375

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  metrics:
    distribution:
      percentiles-histogram.http.server.requests: true
      percentiles-histogram.resilience4j.circuitbreaker.calls: true

resilience4j.retry:
    configs:
        default:
            maxAttempts: 3
            waitDuration: 100
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.util.concurrent.TimeoutException
                - java.io.IOException
    instances:
        poller:
            baseConfig: default

eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
  client:
    enabled: true
    serviceUrl:
      defaultZone:  http://localhost:8762/eureka
    instance:
      hostname:  localhost
#    registerWithEureka: true
#    fetchRegistry: true

spring:
  application:
    name: dl-tor
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/dbdownload
    driverClassName: org.postgresql.Driver
    username: dbuser
    password: dbpass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
springdoc:
  api-docs:
    path: "/api-docs"

plugin:
  monitoringPath: "./plugin"