name: Test on Checkin
on: [push]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest , macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 20
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
    - name: Setup and execute Gradle 'test' task
      uses: gradle/gradle-build-action@v2
      with:
        arguments: clean build test --scan
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
    - name: Upload build reports
      uses: actions/upload-artifact@v3
      if: always() 
      with:
        name: build-reports
        path: build/reports/
    - name: Upload Test XML Files
      uses: actions/upload-artifact@v3
      if: always() 
      with:
        name: test-xmls
        path: /tmp/*.xml